export const userArr = [
  {
    id: 1,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Pending",
  },
  {
    id: 2,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Active",
  },
  {
    id: 3,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Pending",
  },
  {
    id: 4,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Active",
  },
  {
    id: 5,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Pending",
  },
  {
    id: 6,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Active",
  },
  {
    id: 7,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Pending",
  },
  {
    id: 8,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Pending",
  },
  {
    id: 9,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Active",
  },
  {
    id: 10,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Pending",
  },
  {
    id: 11,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Active",
  },
  {
    id: 12,
    name: "Mandeline Eniola",
    username: "Romaguera Jacobson",
    initial: "ME",
    // status: "Pending",
  },
];
